[Home screen] cancel the search when the user selects an item from the search result
tchapgouv/tchap-android-v2 pull request #107
Opened 2021-06-21 13:40 UTC by Florian14

#97

2021-06-22 16:09 UTC, yostyle approved these changes

2021-06-22 20:33 UTC, giomfo requested changes
@Florian14 I tested your PR and have a request: is it possible to cancel the search in background? I mean cancel it when the Home activity is hidden. Currently in case of a room search, the search is cancelled before opening the room

2021-06-24 08:49 UTC, giomfo approved these changes
tests ok
I let @yostyle approved on his side too

2021-06-24 12:51 UTC, yostyle approved these changes

2021-06-24 12:57 UTC, merged