Rename unsigned apk
tchapgouv/tchap-android-v2 pull request #375
Opened 2022-01-24 13:37 UTC by ClaireGizard

#360

2022-01-24 16:03 UTC, yostyle commented
LGTM. I let giom to approve this PR

2022-01-25 13:23 UTC, Florian14 requested changes
Not sure these are the right variants, we should use the `withPinning` variant instead of the `without` one. @giomfo do you confirm?

2022-01-25 14:37 UTC, Florian14 requested changes

2022-01-25 14:37 UTC, Florian14 commented on .github/workflows/build.yml
> +        target: [ GplayBtchapWithoutvoipWithoutpinning, FdroidBtchapWithoutvoipWithoutpinning ]
After discussion IRL, only the gplay variant must be provided **withPinning**

2022-01-25 14:37 UTC, Florian14 commented on .github/workflows/build.yml
> +        target: [ GplayBtchapWithoutvoipWithoutpinning, GplayTchapWithoutvoipWithpinning, FdroidBtchapWithoutvoipWithoutpinning, FdroidTchapWithoutvoipWithoutpinning ]
Please enable pinning for the GplayBtchap target

2022-01-25 14:37 UTC, Florian14 commented on .github/workflows/integration.yml
> +        target: [ GplayBtchapWithoutvoipWithoutpinning, FdroidBtchapWithoutvoipWithoutpinning ]
same here

2022-01-25 14:37 UTC, Florian14 commented on .github/workflows/quality.yml
> +        target: [ GplayBtchapWithoutvoipWithoutpinning, FdroidBtchapWithoutvoipWithoutpinning ]
same here

2022-01-25 14:37 UTC, Florian14 commented on .github/workflows/sanity_test.yml
> +            ./gradlew $CI_GRADLE_ARG_PROPERTIES -PallWarningsAsErrors=false connectedGplayBtchapWithoutvoipWithoutpinningDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=im.vector.
probably here as well

2022-01-25 14:37 UTC, Florian14 commented on .github/workflows/tests.yml
> +        run: ./gradlew clean TestGplayBtchapWithoutvoipWithoutpinningDebugUnitTest $CI_GRADLE_ARG_PROPERTIES -PallWarningsAsErrors=false --stacktrace
same here

2022-01-25 14:37 UTC, Florian14 commented on CONTRIBUTING.md
> +./gradlew lintGplayBtchapWithoutvoipWithoutpinningRelease
same here

2022-01-25 14:37 UTC, Florian14 commented on CONTRIBUTING.md
> +./gradlew testGplayBtchapWithoutvoipWithoutpinningReleaseUnitTest
same here

2022-01-25 14:37 UTC, Florian14 commented on docs/ui-tests.md
> +./gradlew vector:connectedGplayBtchapWithoutvoipWithoutpinningDebugAndroidTest
same here

2022-01-25 15:17 UTC, Florian14 approved these changes
SGTM

2022-01-26 08:41 UTC, giomfo approved these changes
👍

2022-01-26 10:27 UTC, merged